### ISSUE TITLE
Output directory not created automatically for artifact goal

### ISSUE THREAD

**Issue by Madoc** [maven-download-plugin/maven-download-plugin#100]
Example execution (POM excerpt):

    <execution>
        <id>download-postgres-jdbc-driver</id>
        <phase>process-resources</phase>
        <goals>
            <goal>artifact</goal>
        </goals>
        <configuration>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.1.4</version>
            <outputDirectory>target/postgres-jdbc</outputDirectory>
            <outputFileName>postgres-jdbc.jar</outputFileName>
        </configuration>
    </execution>

This fails with the message "Error copying file [...]".

Removing the trailing "/postgres-jdbc" for the `<outputDirectory>` fixes the problem.
The download then goes straight to the `target` folder.

Manually creating the output directory before running the execution also fixes the problem.

This behavior is inconsistent with the `wget` goal, which creates missing subdirectories if needed.

Proposed solution:
Make the `artifact` and `wget` goals behave alike, preferably by automatically creating empty subdirectories if needed.

**Comment by mickaelistria** [comment]
It should work:  https://github.com/maven-download-plugin/maven-download-plugin/blob/master/download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java#L217 . Are you using a recent version?

**Comment by mickaelistria** [comment]
This is actually a dup of #98 which was fixed with #99

**Comment by Madoc** [comment]
I use version `1.4.0`, and it does not work.
Is there a newer version available?

As mentioned, subdirectory creation only works for the `wget` goal, but not for the `artifact` goal.

**Comment by mickaelistria** [comment]
1.4.1-SNAPSHOT should work, as the PR I linked was merged after 1.4.0 release.

**Comment by Madoc** [comment]
Just tried `1.4.1-SNAPSHOT` from the `master` branch, no luck. Same error as reported.

Could it maybe be the case that the `artifact` goal neither calls `mkdir()` nor `mkdirs()`, and therefore was not affected by the PR?

**Comment by mickaelistria** [comment]
I don't know. I let you try to debug it and tell ;) I honestly have no extra-time to spend on this Maven plugins which happens to work perfectly for the use-case I've had in the last 3 years, so I won't be able to help much more...

**Comment by Madoc** [comment]
Understood. Thanks for the help so far! It's appreciated.

Personally, I have no experience with developing Maven plugins. Not very probable that I give it a shot, but maybe...

**Comment by mickaelistria** [comment]
It's honestly not that hard to try. All you need to get started is to use the command line `mvnDebug` instead of `mvn` and to connect your IDE to the port on which the debugger is started. From there, you can monitor code execution against source code in your IDE, it should tell you already a lot.

**Comment by fxnn** [comment]
The problem seems to be that the logic to create directories is in the `unpackFileToDirectory` method, so it's missing in the `copyFileToDirectory` method, used in case we don't unpack (e.g. as the artifact is no ZIP file).

I'll try to prepare a pull request.
