### ISSUE TITLE
readme.md help info outdated

### ISSUE THREAD

**Issue by estani** [maven-download-plugin/maven-download-plugin#103]
the documentation show the help command of:

    mvn help:describe -Dplugin=com.googlecode.maven-download-plugin:maven-download-plugin

which points to the wrong plugin. (old name) It shoud be:

    mvn help:describe -Dplugin=com.googlecode.maven-download-plugin:download-maven-plugin

... or better yet:

    mvn com.googlecode.maven-download-plugin:download-maven-plugin:help

**Comment by mickaelistria** [comment]
Please submit a pull request.

**Comment by estani** [comment]
Well that didn't work as expected... tests failing because of a readme change? At least I tried :) #104
