### ISSUE TITLE
Improve support in m2e

### ISSUE THREAD

**Issue by mickaelistria** [maven-download-plugin/maven-download-plugin#105]
See https://wiki.eclipse.org/M2E_compatible_maven_plugins
The mojos should specify a lifecycle mapping file and use the BuildContext to create content.

**Comment by Catscratch** [comment]
Any chance to get this into release?

**Comment by mickaelistria** [comment]
This is fixed in 1.4.0-SNAPSHOT. Did you try it first?

**Comment by Catscratch** [comment]
I tried 1.4.0-SNAPSHOT and 1.4.1. Both got the problem that "wget" is not covered by lifecycle management. Did I missed something here?
