### ISSUE TITLE
Support encrypted authentication password

### ISSUE THREAD

**Issue by Teknixx** [maven-download-plugin/maven-download-plugin#106]
When downloading a file from a server using basic authentication, the download fails if a serverId is configured and an encrypted password is stored in settings.xml

**Symptom**: HTTP error code 401 (not authenticated)

**Reason**: The password used for the AuthenticationInfo is provided by server.getPassword(). That method only returns the encrypted password. No automatically decryption is performed. So, the encrypted password is sent to the server.The server rejects the requests.

**Tested with**: Maven 3.5.0

Regards
Florian M

**Comment by Teknixx** [comment]
**Solution**:
Add decryption of passwords according to:
https://stackoverflow.com/questions/11314379/maven-password-encryption-for-other-properties#11322060

**Comment by mickaelistria** [comment]
How can the mojo know whether the password is encrypted or not? I'm afraidd proposed patch can break ppl who have stored passwords directly.

**Comment by Teknixx** [comment]
Encrypted password are always encapsulated in braces {...}. Unencrypted passwords are stored directly (braces have to be escaped). See https://maven.apache.org/guides/mini/guide-encryption.html

Additionally, the patch falls back to the old behaviour, if the password can not be decrypted. See decrypt() method.

I've tested the patch with encrypted passwords as well with unencrypted passwords in the settings.xml.

**Comment by mickaelistria** [comment]
Fixed with 762e970f8569f0aafb2a407217ebfd0cca8b4376 and #107.
