### ISSUE TITLE
Not able to download file using download:wget goal

### ISSUE THREAD

**Issue by sandeepsharmadevops** [maven-download-plugin/maven-download-plugin#108]
Hi,

I was using this plugin to download one of the file using HTTP endpoint, below are information about the java, maven version and details about the pom.xml file

--> Java 

![image](https://user-images.githubusercontent.com/12079189/36062947-ec63edb0-0e9b-11e8-947f-f6fa26bc498f.png)

--> Maven

![image](https://user-images.githubusercontent.com/12079189/36062950-0c79f9e6-0e9c-11e8-822f-cb44fd0b4d5f.png)

NOTE: expecting maven download plugin is compatible with above listed java and maven version, if not please let me know about the required versions.

--> pom.xml

![image](https://user-images.githubusercontent.com/12079189/36063025-7de0b77c-0e9d-11e8-9f75-a470a8aea1ae.png)

--> Maven command executed to download
mvn download:wget

--> Issue facing:

[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.0:wget (default-cli) on project Veracode.JAVA.API.Wrapper.Download: The parameters 'uri' for goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.0:wget are missing or invalid -> [Help 1]

Please let me know what mistake am doing in this.

Thanks in advance!!!

**Comment by tomsen-san** [comment]
I see the same problem.

**Comment by toolforger** [comment]
@abstratt "uri" is actually correct. I've been downloading stuff with "uri" all the time.

**Comment by begui** [comment]
Any workaround for this?

**Comment by truenim** [comment]
I've found workaround:
mvn download:wget -Ddownload.url=https://domain.org/file -Ddownload.outputDirectory=resources

**Comment by AlizKaz** [comment]
It seems that configuration written in the "configuration" tag inside "execution" does not effect. For example "url" or "uri" and "unpack" isn't working when they are written in configuration file. On the other hand if you write them in properties with this format "<download.url>someurl</download.url>" and "<download.unpack>aboolean</download.unpack>" it works.

    <properties>
        <java.version>1.8</java.version>
        <download.url>http://samplehost.com/examplefile.zip</download.url>
        <download.unpack>true</download.unpack>
    </properties>

**Comment by musicbyjing** [comment]
Any way to download multiple urls then? You can't have multiples of download.url in <properties>

**Comment by srbala** [comment]
Not able to get this plugin working, ended up using http://www.mojohaus.org/wagon-maven-plugin/. alternate option would be `maven-antrun-plugin:get` task. Be creative and keep the download folder outside of target folder to 'enable' cache from `maven clean`

**Comment by longtimeago** [comment]
@sandeepsharmadevops looks like https://github.com/maven-download-plugin/maven-download-plugin/issues/108#issuecomment-795176288 should fix the issue. Fill free to reopen if not :)
