### ISSUE TITLE
Wget goal does not output anything when -B is set

### ISSUE THREAD

**Issue by gastaldi** [maven-download-plugin/maven-download-plugin#111]
If you run the download:wget mojo using -B, no output (including errors) is displayed

**Comment by longtimeago** [comment]
@gastaldi is that still the case?
Just checked the with latest plugin version (1.6.6)
```
mvn download:wget -Ddownload.url=https -B
```
Outputs
```
Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.7-SNAPSHOT:wget (default-cli) on project simple: Invalid URL: URI is not absolute
```
As expected

**Comment by gastaldi** [comment]
@longtimeago I don' t remember the exact scenario I reproduced this, so I'm going to close it for now and reopen if I manage to reproduce it again. Thanks!
