### ISSUE TITLE
Add @threadSafe to support parallel building

### ISSUE THREAD

**Issue by jontejj** [maven-download-plugin/maven-download-plugin#113]
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in my-project:
[WARNING] com.googlecode.maven-download-plugin:download-maven-plugin:1.2.1
[WARNING] ****************************************************************

Why is it this plugin not marked as threadsafe?

**Comment by mickaelistria** [comment]
Is it plugin really threadsafe?
In any case, contributions are welcome.

**Comment by leonard84** [comment]
Nope not Thread Safe at the moment 
`Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.0:wget (download-sharedconfig) on project acme-module2: IO Error: OverlappingFileLockException`

```xml
 <plugin>
    <groupId>com.googlecode.maven-download-plugin</groupId>
    <artifactId>download-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>download-sharedconfig</id>
            <phase>generate-test-resources</phase>
            <goals>
                <goal>wget</goal>
            </goals>
            <configuration>
                <uri>${sharedconfig.uri}</uri>
                <outputFileName>config.yml</outputFileName>
                <outputDirectory>${maven.multiModuleProjectDirectory}/target</outputDirectory>
                <skipCache>true</skipCache>
                <failOnError>false</failOnError>
            </configuration>
        </execution>
    </executions>
</plugin>
```

We have a team pom that is used in multiple projects and it should download a file once per build in the topmost target directory.

**Comment by leonard84** [comment]
I've created a PR #127 to make WGet thread safe

**Comment by mickaelistria** [comment]
Thanks @leonard84 . I've added a few reviewers on the PR as I'm stepping down as project lead and even contributor for this one (too many things on to do all them well, I have to reduce the load, this project is one I'm unloading). If you don't have any news from them next week, feel free to ping them on the review, and if you receive no answer, I'll give you the key of the shop, making you an admin of the organization.

**Comment by delanym** [comment]
Any luck here? Its a deal breaker not being threadsafe.
