### ISSUE TITLE
Cache fails deserialization fails when upgrading from 1.3.0 to 1.4.1

### ISSUE THREAD

**Issue by mike10004** [maven-download-plugin/maven-download-plugin#120]
If you upgrade the plugin version from 1.3.0 to 1.4.1 and try to wget a file with the cache enabled, an IllegalStateException wrapping a ClassNotFoundException is thrown because the com.googlecode.download.maven.plugin.internal.CachedFileEntry class has been removed (due to a change in the cache implementation.)

You can delete the cache manually, but this might not be possible in build environments where the user doesn't have write access to the filesystem (e.g. on a Jenkins server).

Expected behavior, in my opinion, would at least be to consider an invalid cache to be equivalent to an empty cache, allowing the file to be downloaded fresh.

**Comment by mike10004** [comment]
A workaround for existing projects that depend on the plugin is for them to specify a version-specific cache directory, e.g. `${local-repo}/.cache/maven-download-plugin/1.4.1`. (This is just a theory -- I haven't tested it out).

A potential permanent solution could be to change the plugin's default cache directory to a directory named for the cache format version.

**Comment by mike10004** [comment]
I wrote a unit test that shows the unexpected behavior: https://github.com/mike10004/maven-download-plugin/blob/issue-120-cache-deser/src/test/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndexDeserializationTest.java

My proposed solution would not make it pass -- I think that would require an integration test with the invoker plugin -- but it does demonstrate the IllegalStateException.

**Comment by snicoll** [comment]
Is there anything that can be done for this issue? It means that you can't use two versions of the plugin in the same box. If I create the cache with `1.3.0` and then later on try to use a more recent version of the plugin in a different project, it crashes.

**Comment by mickaelistria** [comment]
Some good things that can be done could be:
1. to move away from plain java serialization of the cache description and implement a serialization to a file (XML or JSon) so we can make the parsing support object changes, or
2. even better, find out some good existing Java project that deals with file caching and manages an index of key->file and that doesn't have any issue of this kind, and use this cache instead of the poor hand-made one which is implemented in the plugin.

**Comment by jblievremont** [comment]
> Expected behavior, in my opinion, would at least be to consider an invalid cache to be equivalent to an empty cache, allowing the file to be downloaded fresh.

Regardless of any possible future implementation, this seems indeed required as a mitigation for existing "old style" caches.
