### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by adamretter** [maven-download-plugin/maven-download-plugin#126]
Hi @mickaelistria would it be possible to get a new release out that includes my PR for Gzip archive support please?

**Comment by mickaelistria** [comment]
I'm personally not available to take care of the release. Maybe @longtimeago can help. If he isn't neither, I'll make you an admin of the organization, so you'll be able to take care of releasing.

**Comment by adamretter** [comment]
@mickaelistria Awesome thanks.

**Comment by adamretter** [comment]
@mickaelistria Any chance I could cut that release please?

**Comment by mickaelistria** [comment]
Can you please create an account on Sonatype's OSSRH Jira ? Then I'll open a ticket to add you as admin for download-maven-plugin and once OSSRH is properly configured on your side, you'll be able to perform the release as descibed in https://github.com/maven-download-plugin/maven-download-plugin/wiki#doing-a-release

**Comment by adamretter** [comment]
@mickaelistria Great, will do! Thanks

**Comment by adamretter** [comment]
@mickaelistria could you give your approval here https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-48777

**Comment by adamretter** [comment]
@mickaelistria Okay I think the release is done. Just waiting for 1.4.2 to sync to Maven Central from OSSRH. Thank you :-)
