### ISSUE TITLE
Ability to configure crerdentials via -D parameters

### ISSUE THREAD

**Issue by s-jepsen** [maven-download-plugin/maven-download-plugin#142]
Could you guys add the ability to define serverId, username, password via. -D parameters.
ex. download.auth.serverId, download.auth.username etc?

**Comment by longtimeago** [comment]
@s-jepsen wouldn't this way work for you?
```xml
      <plugin>
        <groupId>com.googlecode.maven-download-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>1.4.2</version>
        <executions>
          <execution>
			....
            <configuration>
		      ....
              <serverId>${download.auth.serverId}</serverId>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
running with 
```
mvn ... -D download.auth.serverId=your_server_id
```

?

**Comment by s-jepsen** [comment]
HI!

Sorry, no - this would not solve our usecase.

**Comment by longtimeago** [comment]
ok, what is your usecase? which plugin goal do you use (wget, artifact) ?

**Comment by s-jepsen** [comment]
Hi!

My usecase is something along the lines of:
mvn com.googlecode.maven-download-plugin:download-maven-plugin:1.4.2:wget -Ddownload.url=xxx -Ddownload.auth.serverId=central...

The call is used as part of a CI pipeline call.

**Comment by longtimeago** [comment]
@s-jepsen make sense! Contribution is always welcome :)
