### ISSUE TITLE
Help configuring remoteRepositories using MojoExecutor

### ISSUE THREAD

**Issue by nicolasgnr** [maven-download-plugin/maven-download-plugin#155]
I'm using MojoExecutor to execute the `maven-download-plugin` and I couldn't configure accordingly the `remoteRepositories` property used by the plugin to download the files from.

```
Plugin deployFilePlugin = plugin(groupId("org.apache.maven.plugins"), artifactId("maven-deploy-plugin"), version("2.8.2"));
String goal = goal("artifact");

Xpp3Dom pluginConfiguration = configuration(
     element(name("groupId"), groupId),
     element(name("artifactId"), assetId),
     element(name("version"), version),
     element(name("classifier"), classifier),
     element(name("type"), "json"),
     element(name("outputDirectory"), tempDir.getAbsolutePath()),
     element(name("outputFileName"), fileName)
);

ExecutionEnvironment executionEnvironment = executionEnvironment(mavenPluginParameters.getMavenProject(), mavenPluginParameters.getMavenSession(), mavenPluginParameters.getPluginManager());

MojoExecutor.executeMojo(deployFilePlugin, goal, pluginConfiguration, executionEnvironment);
```

I can't just use `element(name("remoteRepositories"), "https://<repo domain>")` since I get an error saying that an `ArtifactRepository` was expected instead of a `String`.

Note: The artifact that I need to download requires authentication 

Any thoughts?

Thanks!

**Comment by longtimeago** [comment]
@nicolasgnr but your example uses `maven-deploy-plugin`, not `maven-download-plugin`. Did I miss something? :)
