### ISSUE TITLE
Support Bearer token authorization

### ISSUE THREAD

**Issue by albx79** [maven-download-plugin/maven-download-plugin#163]
I have the following server section in my settings.xml:
```xml
    <server>
      <id>some-secure-server</id>
      <configuration>
        <httpHeaders>
          <property>
            <name>Authorization</name>
            <value>Bearer ${env.GITHUB_TOKEN}</value>
          </property>
        </httpHeaders>
      </configuration>
    </server>
```

When I try to use the `wget` goal, it fails with the following exception:

```
java.lang.IllegalArgumentException: Username may not be null
    at org.apache.http.util.Args.notNull (Args.java:54)
    at org.apache.http.auth.UsernamePasswordCredentials.<init> (UsernamePasswordCredentials.java:81)
```

This is because WGet assumes that, if I have a `serverId`, the server uses basic auth. This is not always true.

I would expect WGet to use a bearer token if it's specified. Note that, with the server section above, I am able to download maven dependencies normally from the secure server.

**Comment by albx79** [comment]
This is quite urgent for us so I may try and submit a PR in the next few days, unless something is already in the works or you have a specific objection. 

Any advice or input will be greatly appreciated.

**Comment by albx79** [comment]
Alternatively, fixing #8 would provide a suitable workaround, as I could specify the authorization header directly in the POM.

**Comment by longtimeago** [comment]
done via https://github.com/maven-download-plugin/maven-download-plugin/pull/164
