### ISSUE TITLE
No signatures were supplied, skipping file validation

### ISSUE THREAD

**Issue by sgjava** [maven-download-plugin/maven-download-plugin#167]
`--- download-maven-plugin:1.6.0:wget (gpio.h) @ java-periphery ---
No signatures were supplied, skipping file validation
File already exist, skipping`

You can see usage here https://github.com/sgjava/java-periphery/blob/393c50ac06dd6baa2a1735cfaef55ab315486cc5/pom.xml#L51

**Comment by longtimeago** [comment]
@sgjava Not sure what is wrong here?
Signature is not supplied, thus, signature validation is skipped
File already exist at location `${project.basedir}/src/main/native-package/src`, thus, not downloaded again
Did I miss something?

**Comment by sgjava** [comment]
Can this be muted some how? The previous version didn't display this.

**Comment by longtimeago** [comment]
@sgjava ah, got your point :)
I think those messages can be moved to debug level

**Comment by sgjava** [comment]
OK, so you will make change? Thank you in advance.

**Comment by longtimeago** [comment]
yup, why not :)

**Comment by sgjava** [comment]
Thank you kind sir. Will test when available.
