### ISSUE TITLE
nonProxy host configuration ignored

### ISSUE THREAD

**Issue by fmotzkat** [maven-download-plugin/maven-download-plugin#174]
i tried to use the plugin to download load a file with basic authentication and it not work as aspect expected because the nonProxy configuration is ignored in version 1.6.0.
I replaced this code part in WGet.java 
`       
        ProxyInfo proxyInfo = this.wagonManager.getProxy(this.uri.getScheme());
        if (proxyInfo != null && proxyInfo.getHost() != null ) {
`
by 
`       
        ProxyInfo proxyInfo = this.wagonManager.getProxy(this.uri.getScheme());
        boolean useHttpProxy = (proxyInfo != null && proxyInfo.getHost() != null);
        if (proxyInfo != null && proxyInfo.getNonProxyHosts() != null) {
            useHttpProxy = !ProxyUtils.validateNonProxyHosts(proxyInfo, this.uri.getHost());
            getLog().debug("'" + this.uri.getHost() + "' is a " + ((useHttpProxy) ? "" : "non") + " proxy host");
        }
        if (useHttpProxy) {
`
After that it worked fine for me. Could you please add this or a similar patch in the next release? Thanks a lot!
Additional import is needed:
import org.apache.maven.wagon.proxy.ProxyUtils;

**Comment by fmotzkat** [comment]
Hi,
I am afraid the fix you made will not work. If there is a proxy configuration the result will always be true, no matter of the nonProxy settings. There can't be nonProxy settings without proxy configuration of course.
 /**
     * Check if target host should be accessed via proxy.
     * @param proxyInfo Proxy info to check for proxy config.
     * @return True if the target host will be requested via a proxy.
     */
    private boolean useHttpProxy(final ProxyInfo proxyInfo) {
        final boolean result;
        if (proxyInfo == null) {
            result = false;
        } else {
            if (proxyInfo.getHost() != null) {
                result = true;
                getLog().debug(
                    String.format("%s is a proxy host", this.uri.getHost())
                );
            } **else if (proxyInfo.getNonProxyHosts() != null) {
// non reachable code, because no NonProxyHosts without proxy configuration
                result = !ProxyUtils.validateNonProxyHosts(proxyInfo, this.uri.getHost());
                getLog().debug(
                    String.format("%s is a non-proxy host", this.uri.getHost())
                );**
            } else {
                result = false;
            }
        }
        return result;
    }

**Comment by longtimeago** [comment]
@fmotzkat ouch, let me submit another PR. Sorry for the mess :(
