### ISSUE TITLE
Unexpected "Ignoring download failure" warning message

### ISSUE THREAD

**Issue by kriegaex** [maven-download-plugin/maven-download-plugin#185]
Actually, `failOnError` for the `wget` goal is documented to default to `true`, and I did not change it in my POM. I also checked the effective POM for unexpected side effects from any parents or whatever - nothing.

Still, I just had a couple of warnings in my GitHub Actions build, but only as warnings. they did not fail the build like I would have expected. [Here](https://github.com/eclipse/org.aspectj/pull/46/checks) you can see the build logs and also click yourself through to the [POM](https://github.com/kriegaex/org.aspectj/blob/2bc4985745f9568436a47e74feddd5a90f1bf4d7/lib/pom.xml#L57-L185) and all other project details you are interested in.

When looking at the source code
  * https://github.com/maven-download-plugin/maven-download-plugin/blob/5e72171d33c621ec2b354c539ff2f484fbc46dc4/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java#L221-L225
  * https://github.com/maven-download-plugin/maven-download-plugin/blob/5e72171d33c621ec2b354c539ff2f484fbc46dc4/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java#L406
  * https://github.com/maven-download-plugin/maven-download-plugin/blob/5e72171d33c621ec2b354c539ff2f484fbc46dc4/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java#L426

there was nothing obvious that struck me as odd. I can only assume that either the default value is different from what the annotation says or some combination of conditions leads to the build issuing a warning instead of an error.

Please either tell me what I did wrong or fix this problem. I am assuming a problem in the plugin.

**Comment by kriegaex** [comment]
OK, I just found out that even though there are these warnings in my build logs, the downloads actually succeed. What the heck? I see warnings, but then no success messages. In the next step the build failed, so I attributed the failure to these warnings. The actual root cause was something entirely different, the build failure just happened to occur at exactly the same spot as if the downloads had actually really failed. I could not inspect the downloaded files on the server because the failures occurred in a GitHub action and I cannot just browse the file system there.

Just in case you are interested in the real root cause: https://github.com/eclipse/org.aspectj/pull/46/commits/a57efcafcfbab31635048cac9e02bbc55276573c

Before we close this, can you please explain why these warnings appear in the first place, even though the downloads succeed?

**Comment by longtimeago** [comment]
@kriegaex that message is definitely confusing, let me fix that, thanks!
