### ISSUE TITLE
After failed `wget` download, no checksum is compared during the next build

### ISSUE THREAD

**Issue by kriegaex** [maven-download-plugin/maven-download-plugin#186]
If you put something like this into the POM

```xml
<execution>
  <id>download-beanutils-sources</id>
  <phase>generate-resources</phase>
  <goals>
    <goal>wget</goal>
  </goals>
  <configuration>
    <url>https://github.com/apache/commons-beanutils/archive/refs/tags/BEANUTILS_1_4.zip</url>
    <outputDirectory>commons</outputDirectory>
    <outputFileName>commons-beanutils-1.4-sources.jar</outputFileName>
    <sha1>b2c02afe7e6475cd7c811932b8415d171a8afa00</sha1>
  </configuration>
</execution>
```

it works nicely. But if for any reason the file could not be downloaded - e.g. just add "xxx" to the end of the zip file name in order to make the download fail - the build will fail the first time, but save a bogus output file (only a few bytes long). Then when you build again, the build will pass without re-downloading anything, because the plugin thinks the file was already downloaded before. I even supplied a SHA-1 checksum, which obviously it not used by the plugin for verification. Only if the checksum matches, the build should pass, otherwise the build should fail, reporting the checksum mismatch and suggesting to the user to either fix the checksum or fix the download URL.

**Comment by longtimeago** [comment]
@kriegaex nice spot! Thanks a lot for reporting :+1:

**Comment by longtimeago** [comment]
@kriegaex after a closer look, you could specify
```
<checkSignature>true</checkSignature>
```
which is designed exactly to catch such issues. 
I agree, it would be better to check signature by default always and skip the check on existing files with special flag ...
But that's how it is now. Not sure if it worth fixing

**Comment by kriegaex** [comment]
Thanks for your feedback after one month. I think it is worth fixing.

Anyway, the parameter helps. The option does exactly what I want: Not only does it verify signatures of existing, previously downloaded files, but it also leads to re-download if the checksum does not match the specified one.

I am pretty sure I might have found this option myself, if it did not have such a counter-intuitive name. Signatures? It does not check any signatures at all and should be named `verifyChecksum`, `alwaysVerifyChecksum` or even `verifyExistingFileChecksum`, because that is what it does. The description should also explain this clearly. Counter-intuitive option names and help texts which are not actually helping either irritate users or, like in this case, effectively hide useful features from them. Therefore, I suggest to add a new parameter name as an alias for the existing one and declare the latter deprecated, pointing to the new one before removing the deprecated one after a few releases. I guess, this is how it is usually done in Maven plugins.

**Comment by longtimeago** [comment]
@kriegaex yup, `checkSignature` is unfortunate name indeed and you described a nice plan :)
The only thing is time. Let's keep it opened for a while. Will see if I (or someone else) could take care

**Comment by kriegaex** [comment]
If I don't have to wait long for a review and merge (I don't like slow processes, my DNA as an agile coach), I can maybe prepare a PR.

**Comment by longtimeago** [comment]
@kriegaex Usually, I do quick CRs if the issue and the fix are clear :)
So, as always, a contribution is warmly welcome!

**Comment by kriegaex** [comment]
That was fast and painless, thanks.

Feel free to let me know when the next release is out, then I can upgrade and use the renamed parameter and get rid of lengthy explanations in my POMs. 😊

**Comment by longtimeago** [comment]
@kriegaex thank you! :)
Will try to find some time tonight for the release
