### ISSUE TITLE
Support HTTP compression (`wget --compression=auto`)

### ISSUE THREAD

**Issue by mickaelistria** [maven-download-plugin/maven-download-plugin#192]
Some servers (eg VSCode marketplace) seem to only work with clients that are capable of HTTP compression. As a result, it's not possible to use download-maven-plugin to fetch file from those servers.
The WGet goal should support HTTP compression.

**Comment by longtimeago** [comment]
@mickaelistria I tried `wget --compression=auto` and `--compression=none` to download this extension `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/marp-team/vsextensions/marp-vscode/1.3.0/vspackage` and it works fine
Could you, please, provide exact link(s) where the problem can be observed?

**Comment by mkarg** [comment]
Nevertheless, enabling HTTP compression is a very useful feature for this plugin, as transparent compression reduces download times for big binaries considerably. This is as simply as setting a request header and applying unzip on the resulting entity stream.

**Comment by mkarg** [comment]
As maven-download-plugin relies upon Apache Http Client 4.5.x, and as 4.5.x *by default* enables compression *automatically*, actually compression should be working already. Can anybody please *check* and confirm that the current plugin *really* does **not** set the `Content-Encoding` header when sending GET requests?

**Comment by mickaelistria** [comment]
> Can anybody please check and confirm that the current plugin really does not set the Content-Encoding header when sending GET requests?

Can't you do it?

**Comment by mkarg** [comment]
> > Can anybody please check and confirm that the current plugin really does not set the Content-Encoding header when sending GET requests?
> Can't you do it?

I already did and my Wireshark tells me that all works fine (`Content-Encoding: gzip, deflate` is sent when this plugin requests downloads from the server). But as people asked for this feature just few months ago I wonder if it is any different at *their* site *or* why they asked for this feature?

**Comment by mickaelistria** [comment]
I don't remember enough about this issue, it's a sign it's not too important, so let's close.
