### ISSUE TITLE
Make file-writing transactional

### ISSUE THREAD

**Issue by mickaelistria** [maven-download-plugin/maven-download-plugin#2]
Some files may be downloaded at the same time. Hence, we need to make cache index and file downloads transactional.

**Comment by joachim-durchholz-six** [comment]
Maybe Java 7 is standard and this PR should be reconsidered?

**Comment by longtimeago** [comment]
@joachim-durchholz-six which PR do you mean?

**Comment by joachim-durchholz-six** [comment]
@mickaelistria mentioned a PR. I haven't checked myself.

**Comment by longtimeago** [comment]
@joachim-durchholz-six do you mean this one https://github.com/maven-download-plugin/maven-download-plugin/pull/18 ?
It's merged quite a while :) We don't reconsider PRs ;)

**Comment by joachim-durchholz-six** [comment]
Heh. Good thing this issue could be closed then :-)
