### ISSUE TITLE
Ignore Query when computing file name

### ISSUE THREAD

**Issue by mkarg** [maven-download-plugin/maven-download-plugin#204]
The question mark is an invalid character in file names, at least on Windows, so wget fails if a query is part of the URL.

Current Workaround: Provide static file name in the POM.xml.

**Comment by longtimeago** [comment]
@mkarg thanks for reporting! A contribution is warmly welcome :)

**Comment by mkarg** [comment]
My pleasure! :-) https://github.com/maven-download-plugin/maven-download-plugin/pull/207.
