### ISSUE TITLE
FileMappers

### ISSUE THREAD

**Issue by mkarg** [maven-download-plugin/maven-download-plugin#205]
Sometimes it is needed to not unpack *all* content, but just *some*. The Maven Dependency Plugin's unpack task therefore has the ability to apply `FileMappers`. It would be a great addition to the Download Maven Plugin to apply `FileMappers`, too!

**Comment by longtimeago** [comment]
@mkarg I'd appreciate more elaborated example
Also, feel free to contribute ;)

**Comment by mkarg** [comment]
Real world example from one of my actual projects: I need to frequently download latest JRE (from Azul or Adoptium), and I need that ZIP to be unpacked. Unfortunately the ZIP's top level folder is a dynamic name containing the build number. So I do apply a RegEx file mapper which simply cuts away the top level folder.

PR is on the way and works like a charm in my fork already.
