### ISSUE TITLE
Broken Basic Auth in version 1.6.9+

### ISSUE THREAD

**Issue by DmitryZagr** [maven-download-plugin/maven-download-plugin#222]
Starting from version 1.6.9 basic-authorization is broken when downloading files.
[This](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java#L202) filed is always null(this.credentialsProvider) because it is only [set](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java#L176) if HttpFileRequester.Builder.proxyHost is not [null](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java#L162)

Example config:
```xml
<plugin>
    <groupId>com.googlecode.maven-download-plugin</groupId>
    <artifactId>download-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>download</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>wget</goal>
            </goals>
            <configuration>
                <url>${url}</url>
                <unpack>true</unpack>
                <outputDirectory>${download-directory}</outputDirectory>
                <serverId>${artifactory-server-id}</serverId>
                <skipCache>true</skipCache>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by ajarmoniuk** [comment]
I'll check.
