### ISSUE TITLE
(Maintenance) Replace Maven 2 artefacts in the Artifact mojo

### ISSUE THREAD

**Issue by ajarmoniuk** [maven-download-plugin/maven-download-plugin#226]
Move to Maven 3/Maven 4 API in the Artifact mojo.

**Comment by ajarmoniuk** [comment]
@longtimeago it's just an issue for a PR I'm working on. Could you please assign it to me? Thanks.

**Comment by longtimeago** [comment]
fixed via https://github.com/maven-download-plugin/maven-download-plugin/pull/227
