### ISSUE TITLE
Allow ignoring SSL certificate verifications

### ISSUE THREAD

**Issue by yonatang** [maven-download-plugin/maven-download-plugin#236]
Ignoring any SSL certification issues can be useful in some contexts - when downloading resources from a host with self-signed cert, when proxy host changes the certificate, etc. 
In fact, this feature was implicitly requested here: https://github.com/maven-download-plugin/maven-download-plugin/issues/38.

**Comment by vinay-r-m** [comment]
Any idea when this PR shall get merged??

**Comment by longtimeago** [comment]
@vinay-r-m the PR has merge conflicts

**Comment by yonatang** [comment]
hi @longtimeago, the PR was created quite a while ago, and I guess it gone stale since. 
I resolved the conflicts. Do you have privileges to review and approve PRs here? I see there is at least some demand for this enhancement.

**Comment by longtimeago** [comment]
@yonatang good day! Thank you for taking care. Enqueued the PR for review :)

**Comment by louispool** [comment]
Hello! When can we expect a release of the plugin that will include this change?

**Comment by louispool** [comment]
@longtimeago Excellent! That would be very much appreciated!

**Comment by longtimeago** [comment]
@louispool here we go https://github.com/maven-download-plugin/maven-download-plugin/releases/tag/1.8.1

It will take some time to propagate through maven central but you will get it, eventually :)
cheers!

**Comment by louispool** [comment]
@longtimeago Brilliant! Already available through maven central. Thank you so much for the prompt release.  

And thank you @yonatang  for the change!
