### ISSUE TITLE
Support `--offline` option

### ISSUE THREAD

**Issue by marco-brandizi** [maven-download-plugin/maven-download-plugin#24]
This plug-in is great! Thank you for having developed it. I started trying it and I wonder if the Maven --offline option is supported somehow. Ideally, I'd like that, when such option is passed to Maven, the plug-in doesn't try to update an already downloaded file, if this exists, or that it triggers an error, if the file doesn't exist.

I understand a similar behaviour happens because of the cache, but is the --offline flag considered?

Thanks in advance.

**Comment by mickaelistria** [comment]
Actually, it seems to me that the desired behavior is the actual behavior of the plugin, independently of whether build is offline or not.
Feel free to reopen if it's not the case.

**Comment by michael-o** [comment]
Please reopen, while there is this [skip](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/download-maven-plugin/src/main/java/com/googlecode/WGet.java#L136), it still ignores `--offline`. One has to set the property additionally.

**Comment by mickaelistria** [comment]
What would you like --offline to do exactly? What's described in 1st comment is the current behavior of the mojo.

**Comment by michael-o** [comment]
I would expect the plugin to obey that flag and automatically skip all downloads.

**Comment by mickaelistria** [comment]
Ok, got it.

**Comment by mickaelistria** [comment]
To be clear, this is not something I plan to work on soon, but the patch should be easy to write and review, and contributions are welcome ;)
