### ISSUE TITLE
Split into modules

### ISSUE THREAD

**Issue by ajarmoniuk** [maven-download-plugin/maven-download-plugin#243]
I'd like to implement a few features/bugs. Among others the ETag support requested elsewhere, for which it would be better to provide a new implantation of the index.

Ideally as a separate module. Also, the Artifact mojo feels better suited in a separate module. 

For this, it would be a good idea to split the plugin into separate modules.

**Comment by longtimeago** [comment]
@ajarmoniuk I don't see any benefit in modules here. Could you, please, elaborate a bit?

**Comment by ajarmoniuk** [comment]
I mean maven modules and not Java 9+ modules. First of all, the biggest benefit to me is that it could enforce loose coupling across components to a much greater extent than simple packages. One needs to declare cross-module dependencies as well as each module's dependencies. 

Also, different components can have separate needs expressed via dependencies. If you, at some time, decide that one component is no longer needed and can be retired, you can easily see which dependencies are no longer needed.

The downside is that it complicates things: reporting is typically only needed for one module, site is not trivial and typically needs site:stage, etc.

**Comment by longtimeago** [comment]
@ajarmoniuk I know benefits for maven modules :) All you mentioned makes total sense for much bigger projects.
What I meant is that I see absolutely no reason of this complication for this particular project. Thus, please, don't spend time on this
