### ISSUE TITLE
1.7.0 is broken

### ISSUE THREAD

**Issue by hazendaz** [maven-download-plugin/maven-download-plugin#246]
- if .cache/download-maven-plugin exists and artifact is deleted from there, plugin fails to work with 1.7.0.  Whereas 1.6.8 will redownload when missing.

```
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.7.0:wget (default) on project apache-ant: General error: : java.nio.file.NoSuchFileException:...\.m2\repository\.cache\download-maven-plugin\apache-ant-1.10.13-bin.tar.gz_c5f78007b556836b518ca981366e5928
```

- if cache folder is deleted, plugin continually states its downloading and never creates cache.  Dropping back to 1.6.8 will re-create.

- Have another example not shown here that doesn't even attempt to download, gets 2 0 byte attempts and creates a 0 byte entry.  Using wget, not sure if because tar.gz requested or if from github or not.  Dropping to 1.6.8 just works.

Configuration, none, out of the box setup.  Simply using 'wget' option and location to download in this case.  On windows.

You can use https://github.com/hazendaz/ant to reproduce.  Its on 1.7.0 now and broken.  Drop to 1.6.8 and it works.

Maven version in use 3.9.1
Java version in use 17.0.6

Reviewed release notes on this project, nothing mentioned about having to make any changes.

**Comment by hazendaz** [comment]
note: verify critical here.  Bots (Renovate, Dependabot, other) are already slamming updates everywhere.... If changes are expected, release notes better state what exactly.  Neither the documentation which seems rather lacking nor release notes states anything about breaking behaviour.

**Comment by ajarmoniuk** [comment]
> Have another example not shown here that doesn't even attempt to download, gets 2 0 byte attempts and creates a 0 byte entry. Using wget, not sure if because tar.gz requested or if from github or not. Dropping to 1.6.8 just works.

This is very vague. Could you please elaborate on that a little bit? Thanks.

**Comment by hazendaz** [comment]
On zero download. Pushed repo last night that shows that. See hazendaz/atom.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ajarmoniuk** [comment]
Retarding "zero download" -- it's actually a 302 Found temporary redirect returned by the https://github.com/atom/atom/releases/download/v1.60.0/atom-amd64.tar.gz resource you're requesting.

Before 1.7.0, the plugin did have an option `followRedirects`, disabled by default, which was actually being ignored by the plugin, so the redirects were being followed. 1.7.0 included a new backend, which did honor the parameter. So, in order to keep backward compatibility, I'll flip the default.

**Comment by hazendaz** [comment]
Great thank you

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by longtimeago** [comment]
@hazendaz thanks for reporting! :+1: 
would you like to check again snapshot version before we cut a patch release?

**Comment by hazendaz** [comment]
I can check tomorrow evening and let you know thanks.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ajarmoniuk** [comment]
Maybe it would be a good idea to release some qualified "probe" releases? Some projects do this with -alpha or -beta qualifiers.

**Comment by robertpatrick** [comment]
@ajarmoniuk I don't have a way to test the snapshot version.  I tested 1.7.0 on my laptop and it seemed to work fine.  It was only on Jenkins where it failed...

**Comment by ajarmoniuk** [comment]
Among other things, the plugin will create  a zero length file if the target resource returns a redirect code (301, 302, 303). That's what I suspect you're being affected. If it's not that then please could you share the pom.xml and the plugin execution parameters you're using with your CI/CD job? An obfuscated debug (-X) log would be ideal. Thanks.

**Comment by hazendaz** [comment]
> Among other things, issues related to caching -- max cache size of 8 KB prevented the file from being stored in cache (so, the whole cache directory wouldn't get created either if it was deleted by the user).

This seems to be a new feature as old would copy that huge file into cache.  Is there any reason it won't cache that now?  Seems like it should cache something like that IMO.

Other thing I noticed, the case used to be prefixed with the artifactid, now its just a hash.

with 1.6.8 using same ant sample project

```apache-ant-1.10.13-bin.tar.gz_c5f78007b556836b518ca981366e5928```

with 1.7.1 snapshot (built on my machine)

```99053f6e066522bec5d59498bfa3cb87```

I think that is a regression even though it seems like latest will use either of those as the index.ser if not changes is still adhered to and is fine with it without re-downloading.  Although I would rarely look at the cache and most of my use cases are very short lived and usually in cloud, I think its useful to know what the cache item is.

**Comment by ajarmoniuk** [comment]
Hi, cache implementation has been rewritten from scratch using Apache HttpClient Cache as backend. As a result, there are unforeseen issues you've experienced.

> This seems to be a new feature as old would copy that huge file into cache. Is there any reason it won't cache that now? Seems like it should cache something like that IMO.

There's no reason for that. The limitation has been addressed in this snapshot you're using. I don't believe you should be affected by it anymore.

> apache-ant-1.10.13-bin.tar.gz_c5f78007b556836b518ca981366e5928

just pushed a fix for that although that has never been a feature, but indeed a nice to have. We will probably change the format of the index though in some next release.
