### ISSUE TITLE
Download gets compressed

### ISSUE THREAD

**Issue by haavar** [maven-download-plugin/maven-download-plugin#253]
I just upgraded to version 1.7.0 and my download gets compressed. It looks like the output is gzipped. When using version 1.6.7 the file downloads fine.

It behaves like the client is sending the the Accept-Encoding: gzip, but not decompressing the download. I have not confirmed whether that's the case or not.

The file I'm downloading is `https://unpkg.com/@castleio/castle-js@2.1.7/dist/castle.browser.js`.

**Comment by abelsromero** [comment]
I am seeing the same, our builds started failing because we validate with `<md5>` and the files are different. I just obtained the files from the GH-action and they are indeed compressed.

There does not always happen however...

* It happens when downloading Yaml files, for example https://raw.githubusercontent.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/master/data/themes/KaiGenGothicJP-theme.yml. When downloading *.ttf also from raw.githubusercontent.com, it works ok.
* First time, works fine, included Yaml. When running the same pipeline the second time is when we get the zipped file.

**Comment by pkwarren** [comment]
I'm able to reproduce this issue - I can also confirm that the tests are failing with this one change:

```diff
diff --git a/src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java b/src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java
index f23c635..87f4012 100644
--- a/src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java
+++ b/src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java
@@ -503,7 +503,6 @@ public class WGetMojoTest {
             try {
                 createMojo(m -> {
                     setVariableValueToObject(m, "uri", URI.create(wireMock.baseUrl()));
-                    setVariableValueToObject(m, "skipCache", true);
                     setVariableValueToObject(m, "overwrite", true);
                     setVariableValueToObject(m, "outputFileName", OUTPUT_FILE_NAME);
                     setVariableValueToObject(m, key, value);
```

This appears related to the cache refactoring from https://github.com/maven-download-plugin/maven-download-plugin/pull/221. In particular, the cache index is only storing path information (and not all the fields of the `org.apache.http.client.cache.HttpCacheEntry` including headers like `Content-Encoding: gzip`).

This causes the cache to be populated with the response as it was received from the server (which may be compressed) but when loaded from the cache it will lose the header information so it will be treated as an uncompressed entity.

In the meantime I'd recommend either revering to the 1.6.x release or disabling the cache with the `skipCache` parameter: http://maven-download-plugin.github.io/maven-download-plugin/docsite/1.7.1/wget-mojo.html#skipCache

**Comment by ajarmoniuk** [comment]
Hi @pkwarren and @haavar. Thanks for your report. I was puzzled as we certainly didn't put the Accept-Encoding header in the original request, and Content-Encoding must not be sent if the client did not indicate the said encoding in Accept-Encoding. 

However, Apache HttpClient will add the header if request compression is enabled, which it is by default. And so the cached immediate response is indeed compressed. 

Obviously, the simplest solution is then to disable that option, but I think I'll go for the complete removal of the Apache HttpClient cache adoption as its purpose is completely different from what is required for this (which is not an HTTP cache, but a sort of a file buffer).
