### ISSUE TITLE
Allow to manually specify archiver for unpacking

### ISSUE THREAD

**Issue by tomdz** [maven-download-plugin/maven-download-plugin#27]
Some downloads urls don't have a proper file extension, such as https://github.com/lukas-vlcek/bigdesk/zipball/v2.4.0, and for those, the plugin fails with:

```
IO Error: No such archiver: '0'.
```

Would be nice if I could specify the archiver manually in those cases.

**Comment by qqilihq** [comment]
Is there a way for downloading a file just as it is, without performing any decompression? I need to download a `.exe` file which is not compressed, and I get the following error:

```
Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.3.0:wget (download-exe-file) on project my.project: IO Error: No such archiver: 'exe'. -> [Help 1]
```

**Comment by longtimeago** [comment]
workaround is documented in README https://github.com/maven-download-plugin/maven-download-plugin/blob/master/README.md#io-error-no-such-archiver
