### ISSUE TITLE
Support "artifact" parameter in artifact goal

### ISSUE THREAD

**Issue by oillio** [maven-download-plugin/maven-download-plugin#28]
It would be nice if we could pass an artifact parameter in the same way the dependency:get plugin works.
http://maven.apache.org/plugins/maven-dependency-plugin/get-mojo.html#artifact

In that plugin it is a string of the form groupId:artifactId:version[:packaging][:classifier]

**Comment by mykelalvis** [comment]
So how would this be different from `dependency:get` (other than not actually respecting the local repo)?

**Comment by mickaelistria** [comment]
> So how would this be different from dependency:get (other than not actually respecting the local repo)?

+1. Closing.
