### ISSUE TITLE
Support expand filters

### ISSUE THREAD

**Issue by mickaelistria** [maven-download-plugin/maven-download-plugin#3]
When unarchiving, it's not possible to set up filters (excludes/includes) to skip some contents from archives.
It would be useful to support filters for unarchiving.

**Comment by mykelalvis** [comment]
I've looked into the filtering, but don't exactly have a ton of time to devote to non-work stuff.  
I was going to get one of my developers to work on it as a ramp-up project, though, after we get #86 working.

**Comment by longtimeago** [comment]
looks like none is interested in this for years, closing
