### ISSUE TITLE
Upgrade Wagon to 2.5

### ISSUE THREAD

**Issue by kennymacleod** [maven-download-plugin/maven-download-plugin#32]
Versions of Wagon prior to 2.5 (including the 2.4 version referred to in this project's POM) suffer from WAGON-381, which limits the size of the files that can be downloaded. This is fixed in Wagon 2.5, so this just needs bumped in the POM.

**Comment by robinst** [comment]
Looks like this was merged in the meantime: https://github.com/maven-download-plugin/maven-download-plugin/commit/02774119c2697b9080eff4281ee0cc8ff59fb641

**Comment by mickaelistria** [comment]
@robinst  thanks for the follow-up!
