### ISSUE TITLE
Cannot use wget on early Maven lifecycles

### ISSUE THREAD

**Issue by mirandalelo** [maven-download-plugin/maven-download-plugin#34]
The does not work when adding <phase>generate-sources</phase> to the execution.

	<build>
		<plugins>
			<plugin>
				<groupId>com.googlecode.maven-download-plugin</groupId>
				<artifactId>download-maven-plugin</artifactId>
				<version>1.2.1</version>
				<executions>
					<execution>
						<id>atualiza-conteudo</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wget</goal>
						</goals>
						<configuration>
							<url>http://extrastg.globoi.com/api/v3/App/tv-e-lazer/conteudo.json?tiposDeConteudo=gallery</url>
							<outputFileName>AgrupaConteudo</outputFileName>
							<overwrite>true</overwrite>
							<retries>3</retries>
							<outputDirectory>${basedir}/src/main/resources/conteudo</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.jsonschema2pojo</groupId>
				<artifactId>jsonschema2pojo-maven-plugin</artifactId>
				<version>0.4.7</version>
				<configuration>
					<sourceType>json</sourceType>
					<useLongIntegers>true</useLongIntegers>
					
					<annotationStyle>gson</annotationStyle>
					<sourceDirectory>${basedir}/src/main/resources</sourceDirectory>
					<targetPackage>br.infoglobo.json</targetPackage>
				</configuration>
				<executions>
					<execution>
						<id>gera-conteudo</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

![2015-01-30 15_41_20-java - jsontest_pom xml - eclipse](https://cloud.githubusercontent.com/assets/5804242/5980329/85105b94-a896-11e4-949d-da7f2fd96dd4.jpg)

**Comment by mickaelistria** [comment]
Your report is not related to the maven-download-plugin, but more to how m2e handles 3rd party Maven plugins. Please read https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html for more details.
