### ISSUE TITLE
Drop URL Parameters from file downloaded from SourceForge

### ISSUE THREAD

**Issue by einsty** [maven-download-plugin/maven-download-plugin#37]
The Direct Link URL provided by sourceforge has URL parameters by default.  it would be nice if URL params were dropped from the file name when saved, and/or if there is an option to specify what the cached filename should be.

**Comment by mickaelistria** [comment]
The semantic of URLs makes that different parameters can return variations of the same resources (which can end in different binaries), so I'm not sure what you're suggesting is good usage of URLs.
However, can you please give an example of such a sourceforge URL

**Comment by mickaelistria** [comment]
Closing as the initial request seems to be against the semantics of URL.
