### ISSUE TITLE
Pass wget parameters

### ISSUE THREAD

**Issue by longtimeago** [maven-download-plugin/maven-download-plugin#38]
Hi!
There is an issue with `wget` behind a proxy with certificates.
Thus, it would be really cool to have possibility to pass `--no-check-certificate` parameter to `wget`

Thank you!

**Comment by Syzygy24** [comment]
I'm having this same problem. Getting build errors trying to set up swagger because wget won't work behind the proxy.

**Comment by longtimeago** [comment]
@Syzygy24 if this project is manageable I could prepare PR for this feature

**Comment by longtimeago** [comment]
actually, it's not a wget under the hood ... so, the issue is invalid
