### ISSUE TITLE
Unpack/untar of symlinks does not work due to version of plexus archiver

### ISSUE THREAD

**Issue by alxn** [maven-download-plugin/maven-download-plugin#41]
The symptom is that the symlinks becomes 0 byte sized files.

This is the same issue that was affecting Maven `dependency:unpack` in [MDEP-68](https://issues.apache.org/jira/browse/MDEP-68).

It looks like the underlying issue was [PLXCOMP-64](https://raw.githubusercontent.com/sonatype/plexus-archiver/master/jira/PLXCOMP-64.json), and fixed in `plexus-archiver-2.6`, so we just need a `pom.xml` update from [`plexus-archiver-2.4.1`](https://github.com/maven-download-plugin/maven-download-plugin/blob/e5e4462a5914abcc1b8ff63846a891669d1d3979/download-maven-plugin/pom.xml#L117-L121).

**Comment by alxn** [comment]
FYI: @yegor256

**Comment by yegor256** [comment]
@alxn indeed, rather annoying bug, would be great if the product can fix it. thanks!

**Comment by mickaelistria** [comment]
Can you please submit a Pull Request with the necessary change?

**Comment by alxn** [comment]
@mickaelistria sure.

**Comment by alxn** [comment]
@mickaelistria PR in #42.
