### ISSUE TITLE
wget warn instead of fail

### ISSUE THREAD

**Issue by SirWellington** [maven-download-plugin/maven-download-plugin#48]
Sometimes resources are optional. If we can download it, great, if not, then it's ok too.

Is there a way we can specify an option like
```xml
<warnInsteadOfFail>false</warnInsteadOfFail >
```
?

**Comment by SirWellington** [comment]
There goes the pull request.

**Comment by browniefed** [comment]
Will this be shipped at some point? Doesn't seem to be in 1.2.1 @mickaelistria

**Comment by browniefed** [comment]
Just realized this was on 1.2.2-SNAPSHOT, nevermind :). Thanks for the great work

**Comment by longtimeago** [comment]
@SirWellington Looks like its done, right?
Please, close the issue if yes
Thanks

**Comment by SirWellington** [comment]
Yea it’s done. Sorry about the delay.
