### ISSUE TITLE
wget goal fails to honor --batch

### ISSUE THREAD

**Issue by jglick** [maven-download-plugin/maven-download-plugin#52]
Maven downloads by default print a live progress indicator, but switch to a more log-friendly final summary line when `-b`/`--batch` is specified. But this does not work in the case of the `wget` goal of this plugin:

```
mvn -B com.googlecode.maven-download-plugin:download-maven-plugin:1.2.1:wget -DoutputDirectory=. -Ddownload.url=http://server/bigfile | tee out.txt
```

results in an output file with content like

```
…
1184/168910K
1186/168910K
1188/168910K
1192/168910K
1194/168910K
1198/168910K
1200/168910K
1204/168910K
1205/168910K
1209/168910K
1211/168910K
1215/168910K
1217/168910K
1221/168910K
1222/168910K
1226/168910K
1228/168910K
1232/168910K
1234/168910K
…
```

When run from something like Jenkins, the result is an unreadable log file. Compare for example

```
mvn -B org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dartifact=… | tee out.txt
```

which correctly prints just a few lines:

```
[INFO] Downloading: https://repo/art
[INFO] Downloaded: https://repo/art (66391 KB at 2105.5 KB/sec)
```

**Comment by longtimeago** [comment]
@jglick +1
We have the same problem building application with travis-ci - logs become too long

**Comment by longtimeago** [comment]
@mickaelistria Please, take a look at the PR https://github.com/maven-download-plugin/maven-download-plugin/pull/62
Would really appreciate fast turnaround :)

**Comment by longtimeago** [comment]
@jglick the fix is merged. You can try snapshot version
