### ISSUE TITLE
No failOnError in SNAPSHOT

### ISSUE THREAD

**Issue by browniefed** [maven-download-plugin/maven-download-plugin#53]
`failOnError` doesn't seem to appear in the latest 1.3.0-SNAPSHOT. Any chance that it could get released with that option?

**Comment by mickaelistria** [comment]
I just "mvn clean deploy"ed last head from master. This should make latest snapshot include the fix. Can you please give it a try (and close the issue if it's ok for you) ?

**Comment by longtimeago** [comment]
@browniefed is the issue fixed? Could you please try?

**Comment by browniefed** [comment]
Will give it a shot on Monday, moved on from the issue, if it's still an issue I will reopen. Thanks for checking in
