### ISSUE TITLE
Improve download monitor

### ISSUE THREAD

**Issue by amage** [maven-download-plugin/maven-download-plugin#55]
We use maven-download-plugin with Jenkins to download big files ~20-200mb. So the build log has a lot of line like this:
4/24587K
8/24587K
12/24587K
16/24587K
...
24585/24587K
24587/24587K
24587K downloaded

Is it possible to disable download process output or make step large it settings?

**Comment by longtimeago** [comment]
@amage please, try version 1.3.0 running maven build  with `--batch` option

**Comment by amage** [comment]
Much better. Thx!
