### ISSUE TITLE
add expressions to parameter so plugin can be used with command-line

### ISSUE THREAD

**Issue by mickaelistria** [maven-download-plugin/maven-download-plugin#6]
It's currently impossible to use the plugin via command-line since its parameters don't accept expressions, ie they cannot be set using system properties.

**Comment by longtimeago** [comment]
I'm almost sure this is implemented already since I can do
```
mvn download:wget -Ddownload.url=https://github.com/apache/commons-beanutils/archive/refs/tags/commons-beanutils-1.9.4.zip
```
with no issues
