### ISSUE TITLE
URL as key in a map is bad idea

### ISSUE THREAD

**Issue by longtimeago** [maven-download-plugin/maven-download-plugin#79]
I've just found out that using URL as a key in a map is really bad idea, as both ```equals``` and ```hashcode``` implementation will use network on each call.

I think I should turn them back to String
@mickaelistria or, if you have better ideas, I'm all my ears

**Comment by mickaelistria** [comment]
It's what I mentioned in https://github.com/maven-download-plugin/maven-download-plugin/pull/73#discussion_r58358716 . FindBugs recommends using URI:  http://findbugs.sourceforge.net/bugDescriptions.html#DMI_BLOCKING_METHODS_ON_URL

**Comment by longtimeago** [comment]
@mickaelistria sorry, looks like I've missed that comment :(
AFAIK, Maven can't inject URI parameter, so I'll do a conversion. 
Hopefully, I'll take care about the issue this week

**Comment by longtimeago** [comment]
@mickaelistria please, see PR https://github.com/maven-download-plugin/maven-download-plugin/pull/81 with the fix

**Comment by mickaelistria** [comment]
Fixed with https://github.com/maven-download-plugin/maven-download-plugin/commit/e9c1f19c278ad562d2a4869fc1fcdf10e7fae862
