### ISSUE TITLE
Add support for HTTP headers

### ISSUE THREAD

**Issue by Riduidel** [maven-download-plugin/maven-download-plugin#8]
Currently, the maven-download-plugin doesn't allow any HTTP header to be sent with query to server.
It would be really useful for cases where api secrets are required by servers (as a use case to download an example user JSON file from https://developer.wordpress.com/docs/api/1/get/me/)

**Comment by longtimeago** [comment]
@mickaelistria do we still need this issue? Maybe, close it. It's rather old

**Comment by mickaelistria** [comment]
AFAIK, the initial use-case still makes sense and this is not yet available. Why would we close it if it's still a relevant request?

**Comment by longtimeago** [comment]
@mickaelistria uff ... too many concerns are mixed in the issue

**Comment by frederikvanhoyweghen** [comment]
Bump. I have a similar use case where support for setting http headers would be greatly appreciated. Was there any reason why the branched code from @Riduidel was never considered for merging?

**Comment by mickaelistria** [comment]
Is there a pull request ready for that?

**Comment by Riduidel** [comment]
Well, no, but I can take some time to make it pull request ready (that whole thing date from a time where I didn't understand GitHub/Pull Requests/ and so on.
Will try to spend some time making it a good citizen.

**Comment by breandan** [comment]
This feature would be great to have. Many HTTP servers do not accept requests with the default headers and making it impossible to use this plugin.

**Comment by longtimeago** [comment]
custom HTTP headers are supported starting from 1.6.0
https://github.com/maven-download-plugin/maven-download-plugin/releases/tag/1.6.0

Please, check integration test for example https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/it/basicGetWithCustomHeaders/pom.xml
