### ISSUE TITLE
SkipCache or Overwrite does not work?

### ISSUE THREAD

**Issue by moessi1972** [maven-download-plugin/maven-download-plugin#82]
Hello,
is it possible, that "skipCache=true" in combination with "overwrite=true" does not work? With version 1.3.0 for me it is not possible to download a changed WSDL-File. With version 1.2.1 everything works as expected.

Thanks in advance for your soon answer.

Kind regards
Martin

**Comment by moessi1972** [comment]
Does anybody have an idea?

**Comment by mickaelistria** [comment]
Can you provide precise steps to reproduce, or even better, a test case?
cc @longtimeago

**Comment by moessi1972** [comment]
So, the steps to reproduce are:

1. in my pom.xml I have something like this:

`			<plugin>
				<groupId>com.googlecode.maven-download-plugin</groupId>
				<artifactId>download-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>wsdl</id>
						
						<phase>generate-sources</phase>
						<goals>
							<goal>wget</goal>
						</goals>
						<configuration>
			                <url>https://server/HelloWorldWs?wsdl</url>
			                <unpack>false</unpack>
			                <outputDirectory>${basedir}/src/main/resources</outputDirectory>
							<outputFileName>HelloWorldWs.wsdl</outputFileName>
							<skipCache>true</skipCache>
							<skip>false</skip>
							<retries>1</retries>
							<readTimeOut>3000</readTimeOut>
							<overwrite>true</overwrite>
							<failOnError>true</failOnError>
			            </configuration>						
					</execution>
				</executions>
			</plugin>
`
2. Then I run "mvn clean install". The WSDL-File will be written to "src/main/resources".
3. I manipulate the downloaded WSDL-File
4. Again I run "mvn clean install". I would expect, that the file should be new downloaded, but nothing happens. The WSDL-File ist still the same as after step 3.

**Comment by longtimeago** [comment]
@mickaelistria @moessi1972 I'll take a look tonight

**Comment by longtimeago** [comment]
@moessi1972 @mickaelistria Sorry for not so fast response
This bug was fixed in https://github.com/maven-download-plugin/maven-download-plugin/issues/75 but not released yet

**Comment by mickaelistria** [comment]
Dup of #75 as noticed by @longtimeago
