### ISSUE TITLE
Overwrite does not work

### ISSUE THREAD

**Issue by cf1497** [maven-download-plugin/maven-download-plugin#83]
<plugin>
                    <groupId>com.googlecode.maven-download-plugin</groupId>
                    <artifactId>download-maven-plugin</artifactId>
                    <version>1.3.0</version>
                    <executions>
                      <execution>
                        
                        <id>download-file</id>
                        <phase>generate-sources</phase>
                        <goals>
                          <goal>wget</goal>
                        </goals>
                        <configuration>
                          <url>url</url>
                          <outputFileName>file</outputFileName>
                          
                          <outputDirectory>${project.basedir}</outputDirectory>
                          <overwrite>true</overwrite>
                          <skipCache>true</skipCache>
                          <skip>false</skip>
                        </configuration>
                      </execution>
                    </executions>
                 </plugin>

**Comment by cf1497** [comment]
Just overwrite cannot work

**Comment by cf1497** [comment]
If I change the version to be 1.2.0, it works good

**Comment by mickaelistria** [comment]
Dup of #75 . This is currently fixed in snapshot but wasn't released yet. In the meantime you can either use the snapshot or the 1.2.0 release.
