### ISSUE TITLE
Broken file locking.

### ISSUE THREAD

**Issue by cybertiger** [maven-download-plugin/maven-download-plugin#95]
On multimodule projects where each module downloads a file (in this case, checkstyle rules) in the validate phase, sometimes an exception happens due to file locking on the cache directory, specifically when maven invocation is short (e.g. using the versions plugin to update the project version).

It seems the code acquires the lock per invocation on the shared cache index file, and fails if it cannot immediately acquire it.

[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.3.0:wget (download-verto-checkstyle) on project X: IO Error: OverlappingFileLockException -> [Help 1]

**Comment by cybertiger** [comment]
Actually, it's probably more related to the maven argument: -T2C.

**Comment by leonard84** [comment]
#127 would fix this

**Comment by mdaloia** [comment]
It looks like that this issue could be closed now that #127 was closed as the PR #160 was merged and version 1.6.0 released.
