### ISSUE TITLE
Release 1.3.1

### ISSUE THREAD

**Issue by Fizcko** [maven-download-plugin/maven-download-plugin#97]
Hi,

I'm interested about the functionnality to use credentials from settings.xml.

This was fix in 1.3.1-SNAPSHOT (https://github.com/maven-download-plugin/maven-download-plugin/pull/86). Is it possible for you to create a release 1.3.1 on maven central with this fix ?

Regards.

**Comment by mickaelistria** [comment]
Are you already using 1.3.1-SNAPSHOT? Do you confirm this is working as expected for you?

**Comment by Fizcko** [comment]
@mickaelistria Yes i am using 1.3.1-SNAPSHOT and the fix is working perfectly.

**Comment by mickaelistria** [comment]
Ok, I'll try to find an hour to work on it later tomorrow.
However, I have to admit that in the current state, the download-maven-plugin perfectly matches all use-cases I have and I'm not so available to contribute to it anymore. If you or anyone else has more interest in maintaining it than I have, I'd be glad to leave the duties of releasing and so on to someone else ;)

**Comment by Fizcko** [comment]
Thanks a lot @mickaelistria 
With this fix released the "download-maven-plugin" will perfectly matches all my use-cases too :)

**Comment by mickaelistria** [comment]
As there are new features and (backward-compatible) behavior changes since 1.3.0, it's actually going to be a 1.4.0.

**Comment by mickaelistria** [comment]
Release 1.4.0 is completed. Artifact is available on oss.sonatype.org Maven repository and will be mirrored soon to Central.
