### ISSUE TITLE
Artifact goal: Intermediate directories are not created during output directory creation

### ISSUE THREAD

**Issue by zladdi** [maven-download-plugin/maven-download-plugin#98]
The artifact goal uses File.mkdir() to create the output directory. As such, when setting an output directory whose intermediate directory structure does not fully exist yet, the execution of the goal fails.

On the other hand, the wget goal uses File.mkdirs() and is not affected by this issue.

Are there any reasons not to replace mkdir() with mkdirs()?

**Edit**: PR #99 implements the switch to File.mkdirs().

**Comment by mickaelistria** [comment]
Fixed with https://github.com/maven-download-plugin/maven-download-plugin/pull/99/commits/0c90141853f238251bd68fbb8632cafcec73df51 . Thank you!
